on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-2022 ]
        toolkit: [ 14.29, 14.39 ]
        include:
          - os: windows-2019
            toolkit: 14.29
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: amd64_x86
          toolset: ${{ matrix.toolkit }}
          export-path-to-vcvarsall: VCVARSALL
      - name: Setup CMake Ninja Multi-Config
        run: cmake -G "Ninja Multi-Config" --preset x86-multi-config -S . -B out/build/x86-multi-config
      - name: CMake Build
        run: cmake --build out/build/x86-multi-config --target all -j 16
      - name: CMake Install
        run: cmake --build out/build/x86-multi-config --target install
      - name: Convert version to toolkit
        env:
          MSVC_VERSION: ${{ matrix.toolit }}
        run: |
          if ($env:MSVC_VERSION -match "^14.2[0-9]$") {
            echo "TOOLKIT=v142" >> $env:GITHUB_OUTPUT
          }
          if ($env:MSVC_VERSION -match "^14.[34][0-9]$") {
            echo "TOOLKIT=v143" >> $env:GITHUB_OUTPUT
          }
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: UnionAPI-${{ env.TOOLKIT }}-${{ matrix.os }}.zip
          path: out/install/x86-multi-config/*
